M48
; DRILL file {KiCad 8.0.5+1} date 2024-11-03T00:00:47+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-03T00:00:47+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5+1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X45.385Y-83.03
X50.235Y-83.03
T2
X45.085Y-80.0
X50.535Y-80.0
M30
